### ISSUE TITLE
Benchmark Results

### ISSUE THREAD

**Issue by twodawg** [praeclarum/webgpu-torch#4]
M1 16GB Edge:

Benchmark | Time (ms) | Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz | NVIDIA GeForce RTX 3090 | Error
-- | -- | -- | -- | --
unary 1d(1, 'exp') | 3.19 | 0.0019 | 0.0171 |  
unary 1d(1, 'relu') | 3.21 | 0.0020 | 0.0173 |  
unary 1d(1, 'sigmoid') | 2.82 | 0.0020 | 0.0170 |  
unary 1d(1, 'tanh') | 3.27 | 0.0022 | 0.0169 |  
unary 1d(3, 'exp') | 3.28 | 0.0018 | 0.0171 |  
unary 1d(3, 'relu') | 3.24 | 0.0019 | 0.0178 |  
unary 1d(3, 'sigmoid') | 3.25 | 0.0018 | 0.0169 |  
unary 1d(3, 'tanh') | 3.29 | 0.0023 | 0.0167 |  
unary 1d(729, 'exp') | 3.33 | 0.0122 | 0.0235 |  
unary 1d(729, 'relu') | 3.53 | 0.0121 | 0.0236 |  
unary 1d(729, 'sigmoid') | 3.43 | 0.0121 | 0.0230 |  
unary 1d(729, 'tanh') | 3.35 | 0.0138 | 0.0230 |  
unary 1d(2187, 'exp') | 3.42 | 0.0338 | 0.0349 |  
unary 1d(2187, 'relu') | 3.31 | 0.0333 | 0.0356 |  
unary 1d(2187, 'sigmoid') | 3.48 | 0.0380 | 0.0346 |  
unary 1d(2187, 'tanh') | 3.49 | 0.0403 | 0.0354 |  
unary 1d(59049, 'exp') | 4.71 | 0.9219 | 0.5118 |  
unary 1d(59049, 'relu') | 4.25 | 0.8622 | 0.5112 |  
unary 1d(59049, 'sigmoid') | 4.25 | 0.9294 | 0.5123 |  
unary 1d(59049, 'tanh') | 4.24 | 1.0564 | 0.5108 |  
unary 1d(177147, 'exp') | 6.35 | 2.6684 | 1.5115 |  
unary 1d(177147, 'relu') | 6.39 | 2.5438 | 1.4988 |  
unary 1d(177147, 'sigmoid') | 6.38 | 2.7275 | 1.4965 |  
unary 1d(177147, 'tanh') | 6.36 | 3.1460 | 1.4985

**Comment by xenova** [comment]
RTX 2080 8GB
<table class="benchmarks"><thead><tr><th>Benchmark</th><th>Time (ms)</th><th>Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz</th><th>NVIDIA GeForce RTX 3090</th><th>Error</th></tr></thead><tbody><tr><td>unary 1d(1, 'exp')</td><td>3.41</td><td>0.0019</td><td>0.0171</td><td></td></tr><tr><td>unary 1d(1, 'relu')</td><td>3.40</td><td>0.0020</td><td>0.0173</td><td></td></tr><tr><td>unary 1d(1, 'sigmoid')</td><td>3.43</td><td>0.0020</td><td>0.0170</td><td></td></tr><tr><td>unary 1d(1, 'tanh')</td><td>3.42</td><td>0.0022</td><td>0.0169</td><td></td></tr><tr><td>unary 1d(3, 'exp')</td><td>3.41</td><td>0.0018</td><td>0.0171</td><td></td></tr><tr><td>unary 1d(3, 'relu')</td><td>3.42</td><td>0.0019</td><td>0.0178</td><td></td></tr><tr><td>unary 1d(3, 'sigmoid')</td><td>3.47</td><td>0.0018</td><td>0.0169</td><td></td></tr><tr><td>unary 1d(3, 'tanh')</td><td>3.33</td><td>0.0023</td><td>0.0167</td><td></td></tr><tr><td>unary 1d(729, 'exp')</td><td>3.41</td><td>0.0122</td><td>0.0235</td><td></td></tr><tr><td>unary 1d(729, 'relu')</td><td>3.40</td><td>0.0121</td><td>0.0236</td><td></td></tr><tr><td>unary 1d(729, 'sigmoid')</td><td>3.55</td><td>0.0121</td><td>0.0230</td><td></td></tr><tr><td>unary 1d(729, 'tanh')</td><td>3.41</td><td>0.0138</td><td>0.0230</td><td></td></tr><tr><td>unary 1d(2187, 'exp')</td><td>3.47</td><td>0.0338</td><td>0.0349</td><td></td></tr><tr><td>unary 1d(2187, 'relu')</td><td>3.45</td><td>0.0333</td><td>0.0356</td><td></td></tr><tr><td>unary 1d(2187, 'sigmoid')</td><td>3.42</td><td>0.0380</td><td>0.0346</td><td></td></tr><tr><td>unary 1d(2187, 'tanh')</td><td>3.65</td><td>0.0403</td><td>0.0354</td><td></td></tr><tr><td>unary 1d(59049, 'exp')</td><td>5.41</td><td>0.9219</td><td>0.5118</td><td></td></tr><tr><td>unary 1d(59049, 'relu')</td><td>5.56</td><td>0.8622</td><td>0.5112</td><td></td></tr><tr><td>unary 1d(59049, 'sigmoid')</td><td>5.65</td><td>0.9294</td><td>0.5123</td><td></td></tr><tr><td>unary 1d(59049, 'tanh')</td><td>5.70</td><td>1.0564</td><td>0.5108</td><td></td></tr><tr><td>unary 1d(177147, 'exp')</td><td>8.82</td><td>2.6684</td><td>1.5115</td><td></td></tr><tr><td>unary 1d(177147, 'relu')</td><td>8.38</td><td>2.5438</td><td>1.4988</td><td></td></tr><tr><td>unary 1d(177147, 'sigmoid')</td><td>8.84</td><td>2.7275</td><td>1.4965</td><td></td></tr><tr><td>unary 1d(177147, 'tanh')</td><td>8.95</td><td>3.1460</td><td>1.4985</td><td></td></tr></tbody></table>

**Comment by AlexHedley** [comment]
iPhone SE - 16.5

![image](https://github.com/praeclarum/webgpu-torch/assets/1573469/a71496f7-49b7-44d2-89c2-01852af65d5d)

**Comment by mcNets** [comment]
GTX1060  - i7 10th g 32 Gb

<html>
<body>
<h1 style="line-height: 1.2; font-size: 1.875rem; margin: 0.67rem 0px; color: rgb(245, 245, 245); font-family: &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://praeclarum.org/webgpu-torch/" style="color: var(--color-text); text-decoration: none;">webgpu-torch</a><span> </span>benchmarks</h1><div id="benchmarks" style="color: rgb(245, 245, 245); font-family: &quot;Segoe UI&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Benchmark | Time (ms) | Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz | NVIDIA GeForce RTX 3090 | Error
-- | -- | -- | -- | --
unary 1d(1, 'exp') | 3.67 | 0.0019 | 0.0171 |  
unary 1d(1, 'relu') | 3.77 | 0.0020 | 0.0173 |  
unary 1d(1, 'sigmoid') | 3.70 | 0.0020 | 0.0170 |  
unary 1d(1, 'tanh') | 3.54 | 0.0022 | 0.0169 |  
unary 1d(3, 'exp') | 3.68 | 0.0018 | 0.0171 |  
unary 1d(3, 'relu') | 3.62 | 0.0019 | 0.0178 |  
unary 1d(3, 'sigmoid') | 3.61 | 0.0018 | 0.0169 |  
unary 1d(3, 'tanh') | 3.65 | 0.0023 | 0.0167 |  
unary 1d(729, 'exp') | 3.66 | 0.0122 | 0.0235 |  
unary 1d(729, 'relu') | 3.71 | 0.0121 | 0.0236 |  
unary 1d(729, 'sigmoid') | 3.77 | 0.0121 | 0.0230 |  
unary 1d(729, 'tanh') | 3.90 | 0.0138 | 0.0230 |  
unary 1d(2187, 'exp') | 3.73 | 0.0338 | 0.0349 |  
unary 1d(2187, 'relu') | 3.65 | 0.0333 | 0.0356 |  
unary 1d(2187, 'sigmoid') | 3.65 | 0.0380 | 0.0346 |  
unary 1d(2187, 'tanh') | 3.65 | 0.0403 | 0.0354 |  
unary 1d(59049, 'exp') | 6.71 | 0.9219 | 0.5118 |  
unary 1d(59049, 'relu') | 7.05 | 0.8622 | 0.5112 |  
unary 1d(59049, 'sigmoid') | 6.88 | 0.9294 | 0.5123 |  
unary 1d(59049, 'tanh') | 6.84 | 1.0564 | 0.5108 |  
unary 1d(177147, 'exp') | 15.39 | 2.6684 | 1.5115 |  
unary 1d(177147, 'relu') | 15.17 | 2.5438 | 1.4988 |  
unary 1d(177147, 'sigmoid') | 15.02 | 2.7275 | 1.4965 |  
unary 1d(177147, 'tanh') | 15.40 | 3.1460 | 1.4985

</div>
</body>
</html>[webgpu-torch](https://praeclarum.org/webgpu-torch/) benchmarks
Benchmark	Time (ms)	Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz	NVIDIA GeForce RTX 3090	Error
unary 1d(1, 'exp')	3.67	0.0019	0.0171	
unary 1d(1, 'relu')	3.77	0.0020	0.0173	
unary 1d(1, 'sigmoid')	3.70	0.0020	0.0170	
unary 1d(1, 'tanh')	3.54	0.0022	0.0169	
unary 1d(3, 'exp')	3.68	0.0018	0.0171	
unary 1d(3, 'relu')	3.62	0.0019	0.0178	
unary 1d(3, 'sigmoid')	3.61	0.0018	0.0169	
unary 1d(3, 'tanh')	3.65	0.0023	0.0167	
unary 1d(729, 'exp')	3.66	0.0122	0.0235	
unary 1d(729, 'relu')	3.71	0.0121	0.0236	
unary 1d(729, 'sigmoid')	3.77	0.0121	0.0230	
unary 1d(729, 'tanh')	3.90	0.0138	0.0230	
unary 1d(2187, 'exp')	3.73	0.0338	0.0349	
unary 1d(2187, 'relu')	3.65	0.0333	0.0356	
unary 1d(2187, 'sigmoid')	3.65	0.0380	0.0346	
unary 1d(2187, 'tanh')	3.65	0.0403	0.0354	
unary 1d(59049, 'exp')	6.71	0.9219	0.5118	
unary 1d(59049, 'relu')	7.05	0.8622	0.5112	
unary 1d(59049, 'sigmoid')	6.88	0.9294	0.5123	
unary 1d(59049, 'tanh')	6.84	1.0564	0.5108	
unary 1d(177147, 'exp')	15.39	2.6684	1.5115	
unary 1d(177147, 'relu')	15.17	2.5438	1.4988	
unary 1d(177147, 'sigmoid')	15.02	2.7275	1.4965	
unary 1d(177147, 'tanh')	15.40	3.1460	1.4985

**Comment by twodawg** [comment]
Edge Windows 10 Intel i7 12700K, RTX 4090:

Benchmark | Time (ms) | Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz | NVIDIA GeForce RTX 3090 | Error
-- | -- | -- | -- | --
unary 1d(1, 'exp') | 3.21 | 0.0019 | 0.0171 |  
unary 1d(1, 'relu') | 3.16 | 0.0020 | 0.0173 |  
unary 1d(1, 'sigmoid') | 3.68 | 0.0020 | 0.0170 |  
unary 1d(1, 'tanh') | 3.23 | 0.0022 | 0.0169 |  
unary 1d(3, 'exp') | 3.14 | 0.0018 | 0.0171 |  
unary 1d(3, 'relu') | 3.18 | 0.0019 | 0.0178 |  
unary 1d(3, 'sigmoid') | 3.24 | 0.0018 | 0.0169 |  
unary 1d(3, 'tanh') | 2.86 | 0.0023 | 0.0167 |  
unary 1d(729, 'exp') | 3.09 | 0.0122 | 0.0235 |  
unary 1d(729, 'relu') | 3.27 | 0.0121 | 0.0236 |  
unary 1d(729, 'sigmoid') | 3.39 | 0.0121 | 0.0230 |  
unary 1d(729, 'tanh') | 3.20 | 0.0138 | 0.0230 |  
unary 1d(2187, 'exp') | 3.06 | 0.0338 | 0.0349 |  
unary 1d(2187, 'relu') | 3.66 | 0.0333 | 0.0356 |  
unary 1d(2187, 'sigmoid') | 3.19 | 0.0380 | 0.0346 |  
unary 1d(2187, 'tanh') | 2.91 | 0.0403 | 0.0354 |  
unary 1d(59049, 'exp') | 4.26 | 0.9219 | 0.5118 |  
unary 1d(59049, 'relu') | 4.12 | 0.8622 | 0.5112 |  
unary 1d(59049, 'sigmoid') | 4.81 | 0.9294 | 0.5123 |  
unary 1d(59049, 'tanh') | 4.17 | 1.0564 | 0.5108 |  
unary 1d(177147, 'exp') | 6.27 | 2.6684 | 1.5115 |  
unary 1d(177147, 'relu') | 6.45 | 2.5438 | 1.4988 |  
unary 1d(177147, 'sigmoid') | 6.39 | 2.7275 | 1.4965 |  
unary 1d(177147, 'tanh') | 6.83 | 3.1460 | 1.4985

**Comment by praeclarum** [comment]
Thank you everyone!

Since switching the library to lazy evaluation, these number are now a bit old. I'm going to close this thread, feel free to post new numbers!
